# railway.yaml

# Specify the project name
name: flask-app

# Define the services in the project
services:
  # Define the web service
  - name: web
    # Specify the Dockerfile location (if using Docker)
    build:
      dockerfile: Dockerfile

    # Set up the environment variables
    env:
      FLASK_ENV: production
      

    # Define the start command
    start: gunicorn -w 4 -b 0.0.0.0:5001 app:app

    # Define health checks (optional but recommended)
    healthcheck:
      path: /health
      interval: 10s
      timeout: 2s
      retries: 3

    # Expose the necessary port
    ports:
      - 5001
